## Description：
这节课，我们的任务是做一个快手用户的活跃预测。假如我们拿到了一份快手平台记录的关于快手用户的30天一个行为数据集(记录用户注册，登录，视频观看与发布，互动的记录），我们的目标就是根据这个行为数据集预测在未来七天的活跃用户<br><br>

任务分为如下几部分：
>* 任务目标与数据分析
>* 整体模型架构
>* 构建用户特征序列, 生成汇总表
>* 制作标签
>* 建立模型并训练
>* 得出最终的模型结果
>* 知识点和思路总结

In [2]:
"""先导入包"""
import numpy as np
import pandas as pd
import datetime

import tensorflow as tf
from deep_tools import f
from deep_tools import DataGenerator

## 任务目标与数据分析
在这一部分，我们先看看拿到的是一份什么样的数据，然后分析一下我们这个任务到底怎么应该去做。
<br><br>我们会拿到四个表格，分别是：
* 用户注册日志表，记录的是用户什么时候使用什么方式（微信，qq）什么设备（手机，pad）进行注册的快手账号，会有四个字段的信息，注意，day这一列，由于我们搜集的是30天的数据，所以这里的取值是1-30， 表示的是用户第几天的行为，后面那几份数据也是一样。<br>
![](img/1.png)
<br>
* APP启动日志表，记录的是用户在第几天登录过快手app， 两个字段的信息<br>
![](img/2.png)
<br>
* 视频创建日志表， 记录的是用户在第几天创作过视频 <br>
![](img/3.png)
<br>
* 用户行为日志表，这个比较关键，也是我们后面制作特征的主要渠道来源，由用户的行为才能看出用户是不是活跃<br>
![](img/4.png)
<br>

下面，我们就导入数据，详细的看一下这些数据吧

In [2]:
"""读取数据集"""
register = pd.read_csv('user_register_log.txt', sep='\t', names=['user_id', 'register_day', 'register_type', 'device_type'])
register.head()   # 注意这里的register_day 不一定都是1， 1代表我们搜集的30天里面，这个是第1天就注册了，还有的不是第一天注册的，后面会分析。

   user_id  register_day  register_type  device_type
0   744025             1              1          283
1  1270299             1              1          259
2   571220             1              1            2
3  1308501             1              0           23
4   745554             1              2            0

In [3]:
launch = pd.read_csv('app_launch_log.txt', sep='\t', names=['user_id', 'launch_day'])
create = pd.read_csv('video_create_log.txt', sep='\t', names=['user_id', 'create_day'])
activity = pd.read_csv('user_activity_log.txt', sep='\t', names=['user_id', 'act_day', 'page', 'video_id', 'author_id', 'act_type'])
activity.head()

   user_id  act_day  page  video_id  author_id  act_type
0  1062323       22     3   2877472     880271         0
1   639898       17     3    740662     210200         0
2  1260200        5     3   3332414     162866         0
3   817201       22     3   1129617     530246         0
4   817201       23     3   1129617     530246         0

In [4]:
launch.head()   # 记录用户第几天登录过

   user_id  launch_day
0   383135           1
1   330986           4
2   330986           9
3   330986          11
4   330986          12

In [5]:
create.head()   # 记录用户哪一天创建过视频信息

   user_id  create_day
0   720497           1
1   720497           1
2   720497           1
3  1075211           6
4  1075211          12

下面，我们开始对这个数据进行一个解析了， 我们拿到的是一个连续的30天之内用户的一个行为数据，包含了四个数据集，分别记录用户的注册，登录，创建视频，使用行为的信息， 但是有一个问题要注意，就是不一定每个用户的信息都是30天的记录，因为，我们这里有一个注册信息表，里面有一个register_day的字段，这个字段不一定所有用户都是1，即不一定每个用户都是在第一天进行注册的。比如，假设一个用户在第七天才注册的，那么前七天就没有这个用户的信息，假设一个用户是在第25天注册的，那么这个用户只有后五天的数据。 所以这是这个任务的一个难点所在，就是**每个用户的序列长度并不是一样的**， 所有后面我们分析的时候，对于一个用户，先分析是在哪一天注册的，我们再从这一天开始去算。

<br><br> 
再就是我们任务进行一个解析，我们拿到了每个用户的这样的数据，是要预测未来的活跃度，注意这个未来，不是接下来的一两天，而是挺长的一段时间，一个周期这样的。我们这里是预测未来七天内的， 比如有个用户第七天注册了，我们预测的是他第七天到第十四天的活跃度的可能性。这就是我们的目标，基于之前的一段序列数据，来预测未来七天的活跃度的可能性。

## 整体模型架构
这一块，主要是介绍最终介绍的模型长什么样子，根据这个模型，去倒推我们需要去构建什么样的特征和标签（这其实也是一种考虑问题的方式，之前我们可能都是拿到数据，然后特征工程，然后根据我们制作的特征和标签去构建一系列模型，进行预测分类等。 但是有时候我们拿到一个任务之后，或许一下子不太明白究竟要做什么样的数据出来，尤其是这种实际的任务分析。 ），这时候，我们不妨先从模型的角度去考虑任务，先看看什么样的模型适合解决这个任务，然后我们假设已经有了这样的一个模型，那么我们应该考虑这个模型要什么样的输入， 这样，我们再去做相应的输入出来，这也是考虑问题的一种方式吧。 所以这次先从模型开始。<br><br>
关于模型的问题，我们做的虽然说预测用户的活跃度，但可以转化成一个二分类的问题，最后输出就是未来七天时间内，这个用户是否活跃，0或者1. 既然是二分类的问题，那么这里的模型选择就比较多了，什么xgb，lgb，这些优秀的机器学习算法都可以，但是我们分析一下，我们最后拿到的这个数据应该是针对某一个用户，会有从他注册到后面行为的一系列信息，而这些都是时间上进行相关的，比如一个用户第七天注册了，那么我们就有这个用户第七天到第30天的各种行为，也是一种时间序列的预测。关于这种时间序列的预测，如果要使用机器学习的方式，就需要用滑动窗口去切割数据集，并且特征提取上需要使用历史的统计量。<br><br>我们这里使用神经网络的方式，也就是RNN来完成这个任务，这样不需要对输入序列做过多处理，也不使用滑动窗口。毕竟时间的监督学习任务，RNN还是比较擅长的，能够捕捉到时间的这种关联信息。 <br><br>
使用RNN，一般地会想到如下解决方案：以几天内的用户行为序列为输入，以未来七天该用户是否活跃为标签，标注该序列。这是一种Many2One的解决方案。但是这样做的话为了充分利用数据，需要对训练数据做大量的滑窗，以实现数据增广，计算成本高。另外，每个序列只有一个标签，梯度难以传导，导致训练困难。所以我们可以考虑Many2Many结构，即每个输入都对应输出之后7天是否活跃，充分利用监督信息，减轻梯度传到负担，使训练更加容易。我们就可以构建出RNN的大体模型长这样：
![](img/6.png)
<br><br> 这样我们的网络架构就构思出来了，但是这里还有一个细节，就是序列是变长的，就是用户的记录天数是不同的，每个batch中取相同长度的序列，不同batch长度不同，每次随机取某一长度的batch。这时候我们需要使用动态RNN，根据时间序列的长度自己调整。 

那么我们怎么去构建数据呢？ 我们知道上面的都是一些label值，也就是0或者1的这些，表示活跃不活跃。 下面的序列就是我们的输入数据，但是t1,t2,...tn这些数据应该是长什么样子呢？

## 构建用户特征序列
这一块，是我们的重点。我们就是要看看这个用户特征序列究竟怎么样才能构建出来。 思路如下：
>1. 保存每个用户的记录数据
>2. 创建用户字典
>3. 构造用户特征序列

### 保存每个用户的记录数据
既然之前我们说过，每个用户的记录序列长度是不一样子的，所以这个地方我们应该首先先统计每个用户到底有几天的记录数据，把这个长度我们先保存下来。这个比较简单，直接用总天数减去他注册的时间就可以啦。

In [4]:
"""计算序列长度： 持续时间 = 数据总时间 - 注册时间"""
register['seq_length'] = 31 - register['register_day']
register.head()

   user_id  register_day  register_type  device_type  seq_length
0   744025             1              1          283          30
1  1270299             1              1          259          30
2   571220             1              1            2          30
3  1308501             1              0           23          30
4   745554             1              2            0          30

### 创建用户记录字典
根据前面的记录天数，创建一个字典，来存储不同记录天数的用户到底有哪些, key表示记录长度，value表示用户id。
比如只有1天记录的有哪些用户，2天记录的有哪些，...30天完整记录的用户有哪些），这个的目的就是因为我们的用户序列都不等长，也就是每个用户的记录天数不一定一样，这样就导致如果统一喂入神经网络的话，没法组成一个矩阵的形式， 但如果根据记录天数把用户给分开了，那么同一个记录天数下会有很多用户，这些序列是等长的， 那么我们就可以把这些划分成一个batch给神经网络，就好处理了。就是网络的输入接收的每个batch的序列长度要求是相同的，但是不同batch的序列可以不同。

In [5]:
"""根据前面的记录天数，创建一个字典，来存储不同记录天数的用户到底有哪些 """
user_queue = {i: [] for i in range(1,31)}

for index, row in register.iterrows():   # 这个iterrows是对DataFrame进行行遍历，是在数据框中的行进行迭代的一个生成器，它返回每行的索引及一个包含行本身的对象。
    user_queue[row[-1]].append(row[0])     # row[-1]是seq_length, row[0]是user_id

### 构建用户特征
这一块，我们得考虑究竟怎么去提取特征呢？ 首先，得有一个特征的个数，就是针对每个用户，每天的记录，我们得提取多少个特征。 这些特征就是用户的行为，比如什么时候登陆，登陆之后，点没点赞，创没创建视频这些东西（都从数据集里面提取）。 所以对于一个用户来说，我们的输入数据最后应该是一个矩阵，每一行代表着记录的天数，每一列代表一个特征，看下面的图也知道为什么之前要统计不同记录对应的用户了吧，每个用户对应一个矩阵，然后很多个用户合起来就是一个3维的向量，这一个至少是一个立方体的形式。 如果用户的记录不一样的话，就没法进行用户的合并，所以我们这里有了这样一个字典之后，我们就可以把每个记录的用户看成一个batch放入神经网络了。
![](img/7.png)<br>
这一块的思路呢？  我们是要构建用户特征，所以我们定义一个用户序列的类，把所有相关的操作都放到用户序列的里面
> 1. 首先，会构建出每个用户的特征矩阵，就是上面的那种矩阵构建出来，初始化为0， 这里假设特征列为15，即f=15
> 2. 遍历上面的数据表，开始提取相应的特征，把这些特征填入相应用户的相应记录的相应特征中

In [21]:
"""定义一个user_seq类"""
class user_seq:
    
    def __init__(self, register_day, seq_length, n_features):
        """
            register_day: 用户第几天进行的登录
            seq_length: 用户序列的长度，就是记录了几天登录信息， 行数
            n_features: 每天提出的特征个数， 列数
        """
        self.register_day = register_day
        self.seq_length = seq_length
        self.array = np.zeros([seq_length, n_features])   # 这就是上面那个用户对应的矩阵形式，初始化位0
        self.page_rank = np.zeros([self.seq_length])
        self.pointer = 1
    
    # 提取特征填入特征矩阵
    def put_feature(self, feature_number, string):
        for i in string.split(','):
            pos, value = i.split(':')     # 注册后的第几天进行了登录，1为指示符
            self.array[int(pos)-self.register_day, feature_number] = 1   # 从注册后开始记录
    
    
    def get_array(self):
        return self.array
    
    # 得到标签  如果一个用户在未来七天活跃了，那么标记为1
    def get_label(self):
        self.label = np.array([None] * self.seq_length)    # 一个seq_length长度的数组
        active = self.array[:, :12].sum(axis=1)          # 这里选了一部分特征做了个sum，意思是不管是转发，登录，啥的，只要做了就算一次活动
        for i in range(self.seq_length-7):      # 这地方得控制一下，如果一个用户15-30的数据，那么我们标签最多只能到23天，因为30天之后的数据我们没有
            self.label[i] = 1 * (np.sum(active[i+1:i+8]) > 0)    # 这里对于当前的i，如果未来七天内活跃过，那么标签就是1
        
        return self.label

#### 创建每个用户的二维矩阵，初始化为0

In [22]:
"""我们创建用户的那个记录矩阵"""
n_features = 15
data = {row[0]:user_seq(register_day=row[1], seq_length=row[-1], n_features=n_features) for index, row in register.iterrows()}

In [10]:
# 这样就得到了每个用户的初始特征表
data

{744025: <__main__.user_seq at 0x219001ba908>,
 1270299: <__main__.user_seq at 0x219001ba630>,
 571220: <__main__.user_seq at 0x219001ba8d0>,
 1308501: <__main__.user_seq at 0x219001ba828>,
 745554: <__main__.user_seq at 0x219001bad30>,
 1031012: <__main__.user_seq at 0x219001bada0>,
 913297: <__main__.user_seq at 0x219001ba898>,
 266500: <__main__.user_seq at 0x219001badd8>,
 475120: <__main__.user_seq at 0x2197fba4c18>,
 547944: <__main__.user_seq at 0x2197fba4e10>,
 916655: <__main__.user_seq at 0x2197fba4e48>,
 719262: <__main__.user_seq at 0x2197fba4f60>,
 1026175: <__main__.user_seq at 0x2197fba4f98>,
 1140342: <__main__.user_seq at 0x2197fba4da0>,
 688100: <__main__.user_seq at 0x2197fba4c50>,
 1342459: <__main__.user_seq at 0x2197fba4be0>,
 926263: <__main__.user_seq at 0x2197fba44e0>,
 40710: <__main__.user_seq at 0x2197fba4fd0>,
 246954: <__main__.user_seq at 0x2197fba4ba8>,
 153579: <__main__.user_seq at 0x2197fba45f8>,
 161418: <__main__.user_seq at 0x21900661278>,
 649526: <__main__.user_seq at 0x21900661240>,
 376694: <__main__.user_seq at 0x21900661940>,
 1265894: <__main__.user_seq at 0x21900661978>,
 290029: <__main__.user_seq at 0x21900661a90>,
 926952: <__main__.user_seq at 0x21900661358>,
 70931: <__main__.user_seq at 0x21900661f60>,
 319938: <__main__.user_seq at 0x21900661748>,
 711107: <__main__.user_seq at 0x21900661c88>,
 872383: <__main__.user_seq at 0x21900661ef0>,
 324085: <__main__.user_seq at 0x21900661eb8>,
 720967: <__main__.user_seq at 0x21900661400>,
 895912: <__main__.user_seq at 0x21900661908>,
 396421: <__main__.user_seq at 0x21900661b38>,
 605799: <__main__.user_seq at 0x219006617b8>,
 374225: <__main__.user_seq at 0x219006617f0>,
 188120: <__main__.user_seq at 0x21900661828>,
 4416: <__main__.user_seq at 0x21900661860>,
 245385: <__main__.user_seq at 0x21900661898>,
 1244564: <__main__.user_seq at 0x21900661f98>,
 321610: <__main__.user_seq at 0x219006610b8>,
 998568: <__main__.user_seq at 0x21900661080>,
 362447: <__main__.user_seq at 0x21900661048>,
 508312: <__main__.user_seq at 0x21900661198>,
 828824: <__main__.user_seq at 0x21900661208>,
 604296: <__main__.user_seq at 0x21900661390>,
 1040779: <__main__.user_seq at 0x21900661e80>,
 104515: <__main__.user_seq at 0x21900661b70>,
 909345: <__main__.user_seq at 0x21900661c50>,
 584573: <__main__.user_seq at 0x21900661780>,
 809615: <__main__.user_seq at 0x21900661550>,
 705594: <__main__.user_seq at 0x21900661160>,
 544673: <__main__.user_seq at 0x219006610f0>,
 1353252: <__main__.user_seq at 0x21900661dd8>,
 1228936: <__main__.user_seq at 0x21900661668>,
 130304: <__main__.user_seq at 0x21900661f28>,
 636433: <__main__.user_seq at 0x21900661e48>,
 649913: <__main__.user_seq at 0x21900661470>,
 300198: <__main__.user_seq at 0x21900661128>,
 958588: <__main__.user_seq at 0x21900661e10>,
 365947: <__main__.user_seq at 0x219006619b0>,
 546663: <__main__.user_seq at 0x219006618d0>,
 358836: <__main__.user_seq at 0x219006614e0>,
 572651: <__main__.user_seq at 0x21900661d30>,
 200677: <__main__.user_seq at 0x21900661a58>,
 121072: <__main__.user_seq at 0x21900661c18>,
 283372: <__main__.user_seq at 0x21900661ac8>,
 1046808: <__main__.user_seq at 0x21900661438>,
 286389: <__main__.user_seq at 0x21900661cc0>,
 785752: <__main__.user_seq at 0x21900661d68>,
 65439: <__main__.user_seq at 0x21900661a20>,
 1070734: <__main__.user_seq at 0x21900661ba8>,
 409296: <__main__.user_seq at 0x219006616a0>,
 507130: <__main__.user_seq at 0x219006613c8>,
 46089: <__main__.user_seq at 0x219006614a8>,
 363195: <__main__.user_seq at 0x219006616d8>,
 826213: <__main__.user_seq at 0x219006619e8>,
 1095380: <__main__.user_seq at 0x21900661cf8>,
 742578: <__main__.user_seq at 0x21900661da0>,
 278433: <__main__.user_seq at 0x219006611d0>,
 323276: <__main__.user_seq at 0x21900661518>,
 1080404: <__main__.user_seq at 0x219006612b0>,
 371793: <__main__.user_seq at 0x219006615c0>,
 581535: <__main__.user_seq at 0x21900661710>,
 623713: <__main__.user_seq at 0x21900661b00>,
 613814: <__main__.user_seq at 0x21900661588>,
 1230657: <__main__.user_seq at 0x21900661fd0>,
 181217: <__main__.user_seq at 0x219006615f8>,
 393403: <__main__.user_seq at 0x21900661be0>,
 647111: <__main__.user_seq at 0x21900661630>,
 301007: <__main__.user_seq at 0x21900669048>,
 1720: <__main__.user_seq at 0x21900669080>,
 135240: <__main__.user_seq at 0x219006690b8>,
 1005097: <__main__.user_seq at 0x219006690f0>,
 1265157: <__main__.user_seq at 0x21900669128>,
 422203: <__main__.user_seq at 0x21900669160>,
 491162: <__main__.user_seq at 0x21900669198>,
 392276: <__main__.user_seq at 0x219006691d0>,
 1119103: <__main__.user_seq at 0x21900669208>,
 493601: <__main__.user_seq at 0x21900669240>,
 987199: <__main__.user_seq at 0x21900669278>,
 428929: <__main__.user_seq at 0x219006692b0>,
 764894: <__main__.user_seq at 0x219006692e8>,
 901027: <__main__.user_seq at 0x21900669320>,
 716335: <__main__.user_seq at 0x21900669358>,
 1132054: <__main__.user_seq at 0x21900669390>,
 1201394: <__main__.user_seq at 0x219006693c8>,
 79180: <__main__.user_seq at 0x21900669400>,
 363940: <__main__.user_seq at 0x21900669438>,
 1171561: <__main__.user_seq at 0x21900669470>,
 29588: <__main__.user_seq at 0x219006694a8>,
 225105: <__main__.user_seq at 0x219006694e0>,
 479488: <__main__.user_seq at 0x21900669518>,
 1349377: <__main__.user_seq at 0x21900669550>,
 755950: <__main__.user_seq at 0x21900669588>,
 867067: <__main__.user_seq at 0x219006695c0>,
 1208320: <__main__.user_seq at 0x219006695f8>,
 644685: <__main__.user_seq at 0x21900669630>,
 580269: <__main__.user_seq at 0x21900669668>,
 1278006: <__main__.user_seq at 0x219006696a0>,
 900759: <__main__.user_seq at 0x219006696d8>,
 301088: <__main__.user_seq at 0x21900669710>,
 846124: <__main__.user_seq at 0x21900669748>,
 873341: <__main__.user_seq at 0x21900669780>,
 373134: <__main__.user_seq at 0x219006697b8>,
 547864: <__main__.user_seq at 0x219006697f0>,
 1145926: <__main__.user_seq at 0x21900669828>,
 741300: <__main__.user_seq at 0x21900669860>,
 685607: <__main__.user_seq at 0x21900669898>,
 1096768: <__main__.user_seq at 0x219006698d0>,
 544078: <__main__.user_seq at 0x21900669908>,
 500537: <__main__.user_seq at 0x21900669940>,
 1126528: <__main__.user_seq at 0x21900669978>,
 470633: <__main__.user_seq at 0x219006699b0>,
 1260044: <__main__.user_seq at 0x219006699e8>,
 1147129: <__main__.user_seq at 0x21900669a20>,
 708206: <__main__.user_seq at 0x21900669a58>,
 578505: <__main__.user_seq at 0x21900669a90>,
 473398: <__main__.user_seq at 0x21900669ac8>,
 805787: <__main__.user_seq at 0x21900669b00>,
 905493: <__main__.user_seq at 0x21900669b38>,
 706631: <__main__.user_seq at 0x21900669b70>,
 875685: <__main__.user_seq at 0x21900669ba8>,
 969252: <__main__.user_seq at 0x21900669be0>,
 24482: <__main__.user_seq at 0x21900669c18>,
 935166: <__main__.user_seq at 0x21900669c50>,
 1316877: <__main__.user_seq at 0x21900669c88>,
 1163109: <__main__.user_seq at 0x21900669cc0>,
 657176: <__main__.user_seq at 0x21900669cf8>,
 1024790: <__main__.user_seq at 0x21900669d30>,
 1216256: <__main__.user_seq at 0x21900669d68>,
 908794: <__main__.user_seq at 0x21900669da0>,
 154609: <__main__.user_seq at 0x21900669dd8>,
 1283254: <__main__.user_seq at 0x21900669e10>,
 498488: <__main__.user_seq at 0x21900669e48>,
 969395: <__main__.user_seq at 0x21900669e80>,
 64315: <__main__.user_seq at 0x21900669eb8>,
 354563: <__main__.user_seq at 0x21900669ef0>,
 1356592: <__main__.user_seq at 0x21900669f28>,
 706245: <__main__.user_seq at 0x21900669f60>,
 173080: <__main__.user_seq at 0x21900669f98>,
 315508: <__main__.user_seq at 0x21900669fd0>,
 889586: <__main__.user_seq at 0x21900674048>,
 932852: <__main__.user_seq at 0x21900674080>,
 196795: <__main__.user_seq at 0x219006740b8>,
 700459: <__main__.user_seq at 0x219006740f0>,
 784518: <__main__.user_seq at 0x21900674128>,
 1149160: <__main__.user_seq at 0x21900674160>,
 251319: <__main__.user_seq at 0x21900674198>,
 526703: <__main__.user_seq at 0x219006741d0>,
 320032: <__main__.user_seq at 0x21900674208>,
 119327: <__main__.user_seq at 0x21900674240>,
 627445: <__main__.user_seq at 0x21900674278>,
 1333459: <__main__.user_seq at 0x219006742b0>,
 588012: <__main__.user_seq at 0x219006742e8>,
 12034: <__main__.user_seq at 0x21900674320>,
 146820: <__main__.user_seq at 0x21900674358>,
 1243074: <__main__.user_seq at 0x21900674390>,
 271512: <__main__.user_seq at 0x219006743c8>,
 1257585: <__main__.user_seq at 0x21900674400>,
 1124798: <__main__.user_seq at 0x21900674438>,
 82342: <__main__.user_seq at 0x21900674470>,
 1045093: <__main__.user_seq at 0x219006744a8>,
 1087280: <__main__.user_seq at 0x219006744e0>,
 182906: <__main__.user_seq at 0x21900674518>,
 934918: <__main__.user_seq at 0x21900674550>,
 856907: <__main__.user_seq at 0x21900674588>,
 564522: <__main__.user_seq at 0x219006745c0>,
 889866: <__main__.user_seq at 0x219006745f8>,
 986839: <__main__.user_seq at 0x21900674630>,
 551821: <__main__.user_seq at 0x21900674668>,
 988294: <__main__.user_seq at 0x219006746a0>,
 1022936: <__main__.user_seq at 0x219006746d8>,
 349043: <__main__.user_seq at 0x21900674710>,
 1010794: <__main__.user_seq at 0x21900674748>,
 1274576: <__main__.user_seq at 0x21900674780>,
 109973: <__main__.user_seq at 0x219006747b8>,
 134299: <__main__.user_seq at 0x219006747f0>,
 1005835: <__main__.user_seq at 0x21900674828>,
 864582: <__main__.user_seq at 0x21900674860>,
 1293122: <__main__.user_seq at 0x21900674898>,
 896835: <__main__.user_seq at 0x219006748d0>,
 630631: <__main__.user_seq at 0x21900674908>,
 1121791: <__main__.user_seq at 0x21900674940>,
 1038314: <__main__.user_seq at 0x21900674978>,
 123473: <__main__.user_seq at 0x219006749b0>,
 916883: <__main__.user_seq at 0x219006749e8>,
 627561: <__main__.user_seq at 0x21900674a20>,
 1343228: <__main__.user_seq at 0x21900674a58>,
 1134049: <__main__.user_seq at 0x21900674a90>,
 1097140: <__main__.user_seq at 0x21900674ac8>,
 192598: <__main__.user_seq at 0x21900674b00>,
 1084176: <__main__.user_seq at 0x21900674b38>,
 699788: <__main__.user_seq at 0x21900674b70>,
 1206272: <__main__.user_seq at 0x21900674ba8>,
 1357808: <__main__.user_seq at 0x21900674be0>,
 879812: <__main__.user_seq at 0x21900674c18>,
 178800: <__main__.user_seq at 0x21900674c50>,
 6142: <__main__.user_seq at 0x21900674c88>,
 744006: <__main__.user_seq at 0x21900674cc0>,
 498016: <__main__.user_seq at 0x21900674cf8>,
 603422: <__main__.user_seq at 0x21900674d30>,
 817397: <__main__.user_seq at 0x21900674d68>,
 279797: <__main__.user_seq at 0x21900674da0>,
 42931: <__main__.user_seq at 0x21900674dd8>,
 477509: <__main__.user_seq at 0x21900674e10>,
 768177: <__main__.user_seq at 0x21900674e48>,
 1275284: <__main__.user_seq at 0x21900674e80>,
 844601: <__main__.user_seq at 0x21900674eb8>,
 82524: <__main__.user_seq at 0x21900674ef0>,
 73158: <__main__.user_seq at 0x21900674f28>,
 1139294: <__main__.user_seq at 0x21900674f60>,
 1102709: <__main__.user_seq at 0x21900674f98>,
 52918: <__main__.user_seq at 0x21900674fd0>,
 85132: <__main__.user_seq at 0x2190067b048>,
 23948: <__main__.user_seq at 0x2190067b080>,
 201951: <__main__.user_seq at 0x2190067b0b8>,
 343886: <__main__.user_seq at 0x2190067b0f0>,
 671062: <__main__.user_seq at 0x2190067b128>,
 1039738: <__main__.user_seq at 0x2190067b160>,
 310025: <__main__.user_seq at 0x2190067b198>,
 1266850: <__main__.user_seq at 0x2190067b1d0>,
 590886: <__main__.user_seq at 0x2190067b2b0>,
 942055: <__main__.user_seq at 0x2190067b2e8>,
 694183: <__main__.user_seq at 0x2190067b320>,
 1302790: <__main__.user_seq at 0x2190067b358>,
 1352813: <__main__.user_seq at 0x2190067b390>,
 219457: <__main__.user_seq at 0x2190067b3c8>,
 1273778: <__main__.user_seq at 0x2190067b400>,
 615136: <__main__.user_seq at 0x2190067b438>,
 692306: <__main__.user_seq at 0x2190067b470>,
 234824: <__main__.user_seq at 0x2190067b4a8>,
 797113: <__main__.user_seq at 0x2190067b4e0>,
 1168061: <__main__.user_seq at 0x2190067b518>,
 933116: <__main__.user_seq at 0x2190067b550>,
 675189: <__main__.user_seq at 0x2190067b588>,
 117234: <__main__.user_seq at 0x2190067b5c0>,
 473215: <__main__.user_seq at 0x2190067b5f8>,
 693597: <__main__.user_seq at 0x2190067b630>,
 292217: <__main__.user_seq at 0x2190067b668>,
 318189: <__main__.user_seq at 0x2190067b6a0>,
 893024: <__main__.user_seq at 0x2190067b6d8>,
 1147778: <__main__.user_seq at 0x2190067b710>,
 75464: <__main__.user_seq at 0x2190067b748>,
 355948: <__main__.user_seq at 0x2190067b780>,
 1141243: <__main__.user_seq at 0x2190067b7b8>,
 885314: <__main__.user_seq at 0x2190067b7f0>,
 473037: <__main__.user_seq at 0x2190067b828>,
 1161976: <__main__.user_seq at 0x2190067b860>,
 1105249: <__main__.user_seq at 0x2190067b898>,
 1034711: <__main__.user_seq at 0x2190067b8d0>,
 444663: <__main__.user_seq at 0x2190067b908>,
 629789: <__main__.user_seq at 0x2190067b940>,
 684292: <__main__.user_seq at 0x2190067b978>,
 1220188: <__main__.user_seq at 0x2190067b9b0>,
 38479: <__main__.user_seq at 0x2190067b9e8>,
 1166260: <__main__.user_seq at 0x2190067ba20>,
 739798: <__main__.user_seq at 0x2190067ba58>,
 1023596: <__main__.user_seq at 0x2190067ba90>,
 731282: <__main__.user_seq at 0x2190067bac8>,
 759110: <__main__.user_seq at 0x2190067bb00>,
 327708: <__main__.user_seq at 0x2190067bb38>,
 129695: <__main__.user_seq at 0x2190067bb70>,
 1344791: <__main__.user_seq at 0x2190067bba8>,
 1096813: <__main__.user_seq at 0x2190067bbe0>,
 848341: <__main__.user_seq at 0x2190067bc18>,
 1068843: <__main__.user_seq at 0x2190067bc50>,
 419912: <__main__.user_seq at 0x2190067bc88>,
 823586: <__main__.user_seq at 0x2190067bcc0>,
 296386: <__main__.user_seq at 0x2190067bcf8>,
 1161945: <__main__.user_seq at 0x2190067bd30>,
 200400: <__main__.user_seq at 0x2190067bd68>,
 1195373: <__main__.user_seq at 0x2190067bda0>,
 973391: <__main__.user_seq at 0x2190067bdd8>,
 65575: <__main__.user_seq at 0x2190067be10>,
 837576: <__main__.user_seq at 0x2190067be48>,
 298119: <__main__.user_seq at 0x2190067be80>,
 1358198: <__main__.user_seq at 0x2190067beb8>,
 375546: <__main__.user_seq at 0x2190067bef0>,
 544646: <__main__.user_seq at 0x2190067bf28>,
 607849: <__main__.user_seq at 0x2190067bf60>,
 354025: <__main__.user_seq at 0x2190067bf98>,
 1331521: <__main__.user_seq at 0x2190067bfd0>,
 1191566: <__main__.user_seq at 0x21900680048>,
 199629: <__main__.user_seq at 0x21900680080>,
 1236008: <__main__.user_seq at 0x219006800b8>,
 214542: <__main__.user_seq at 0x219006800f0>,
 350622: <__main__.user_seq at 0x21900680128>,
 190614: <__main__.user_seq at 0x21900680160>,
 964475: <__main__.user_seq at 0x21900680198>,
 45704: <__main__.user_seq at 0x219006801d0>,
 878391: <__main__.user_seq at 0x21900680208>,
 1105526: <__main__.user_seq at 0x21900680240>,
 164445: <__main__.user_seq at 0x21900680278>,
 488255: <__main__.user_seq at 0x219006802b0>,
 143944: <__main__.user_seq at 0x219006802e8>,
 802240: <__main__.user_seq at 0x21900680320>,
 1314381: <__main__.user_seq at 0x21900680358>,
 863520: <__main__.user_seq at 0x21900680390>,
 322780: <__main__.user_seq at 0x219006803c8>,
 1115620: <__main__.user_seq at 0x21900680400>,
 1004240: <__main__.user_seq at 0x21900680438>,
 91631: <__main__.user_seq at 0x21900680470>,
 1306292: <__main__.user_seq at 0x219006804a8>,
 305295: <__main__.user_seq at 0x219006804e0>,
 46877: <__main__.user_seq at 0x21900680518>,
 1366339: <__main__.user_seq at 0x21900680550>,
 1055951: <__main__.user_seq at 0x21900680588>,
 1186938: <__main__.user_seq at 0x219006805c0>,
 253904: <__main__.user_seq at 0x219006805f8>,
 78349: <__main__.user_seq at 0x21900680630>,
 1260188: <__main__.user_seq at 0x21900680668>,
 1016609: <__main__.user_seq at 0x219006806a0>,
 993751: <__main__.user_seq at 0x219006806d8>,
 826191: <__main__.user_seq at 0x21900680710>,
 1042464: <__main__.user_seq at 0x21900680748>,
 600907: <__main__.user_seq at 0x21900680780>,
 75238: <__main__.user_seq at 0x219006807b8>,
 600462: <__main__.user_seq at 0x219006807f0>,
 43426: <__main__.user_seq at 0x21900680828>,
 1016709: <__main__.user_seq at 0x21900680860>,
 1076150: <__main__.user_seq at 0x21900680898>,
 861690: <__main__.user_seq at 0x219006808d0>,
 1346568: <__main__.user_seq at 0x21900680908>,
 461873: <__main__.user_seq at 0x21900680940>,
 1102232: <__main__.user_seq at 0x21900680978>,
 1056760: <__main__.user_seq at 0x219006809b0>,
 1360047: <__main__.user_seq at 0x219006809e8>,
 548821: <__main__.user_seq at 0x21900680a20>,
 525224: <__main__.user_seq at 0x21900680a58>,
 626427: <__main__.user_seq at 0x21900680a90>,
 354599: <__main__.user_seq at 0x21900680ac8>,
 892684: <__main__.user_seq at 0x21900680b00>,
 294385: <__main__.user_seq at 0x21900680b38>,
 488384: <__main__.user_seq at 0x21900680b70>,
 1127998: <__main__.user_seq at 0x21900680ba8>,
 171819: <__main__.user_seq at 0x21900680be0>,
 1197226: <__main__.user_seq at 0x21900680c18>,
 66852: <__main__.user_seq at 0x21900680c50>,
 1111524: <__main__.user_seq at 0x21900680c88>,
 1103093: <__main__.user_seq at 0x21900680cc0>,
 166587: <__main__.user_seq at 0x21900680cf8>,
 1090147: <__main__.user_seq at 0x21900680d30>,
 401543: <__main__.user_seq at 0x21900680d68>,
 979232: <__main__.user_seq at 0x21900680da0>,
 1079600: <__main__.user_seq at 0x21900680dd8>,
 231285: <__main__.user_seq at 0x21900680e10>,
 909695: <__main__.user_seq at 0x21900680e48>,
 259356: <__main__.user_seq at 0x21900680e80>,
 482351: <__main__.user_seq at 0x21900680eb8>,
 45605: <__main__.user_seq at 0x21900680ef0>,
 1308171: <__main__.user_seq at 0x21900680f28>,
 307872: <__main__.user_seq at 0x21900680f60>,
 308051: <__main__.user_seq at 0x21900680f98>,
 491446: <__main__.user_seq at 0x21900680fd0>,
 550643: <__main__.user_seq at 0x21900689048>,
 347099: <__main__.user_seq at 0x21900689080>,
 647478: <__main__.user_seq at 0x219006890b8>,
 1351534: <__main__.user_seq at 0x219006890f0>,
 367241: <__main__.user_seq at 0x21900689128>,
 578309: <__main__.user_seq at 0x21900689160>,
 410784: <__main__.user_seq at 0x21900689198>,
 374871: <__main__.user_seq at 0x219006891d0>,
 820690: <__main__.user_seq at 0x21900689208>,
 80545: <__main__.user_seq at 0x21900689240>,
 482040: <__main__.user_seq at 0x21900689278>,
 660628: <__main__.user_seq at 0x219006892b0>,
 657616: <__main__.user_seq at 0x219006892e8>,
 406622: <__main__.user_seq at 0x21900689320>,
 46519: <__main__.user_seq at 0x21900689358>,
 440020: <__main__.user_seq at 0x21900689390>,
 838388: <__main__.user_seq at 0x219006893c8>,
 372368: <__main__.user_seq at 0x21900689400>,
 1028559: <__main__.user_seq at 0x21900689438>,
 1014699: <__main__.user_seq at 0x21900689470>,
 311119: <__main__.user_seq at 0x219006894a8>,
 540632: <__main__.user_seq at 0x219006894e0>,
 1174064: <__main__.user_seq at 0x21900689518>,
 1288325: <__main__.user_seq at 0x21900689550>,
 574156: <__main__.user_seq at 0x21900689588>,
 277490: <__main__.user_seq at 0x219006895c0>,
 1359548: <__main__.user_seq at 0x219006895f8>,
 853695: <__main__.user_seq at 0x21900689630>,
 53864: <__main__.user_seq at 0x21900689668>,
 158030: <__main__.user_seq at 0x219006896a0>,
 497272: <__main__.user_seq at 0x219006896d8>,
 699878: <__main__.user_seq at 0x21900689710>,
 908320: <__main__.user_seq at 0x21900689748>,
 747066: <__main__.user_seq at 0x21900689780>,
 294696: <__main__.user_seq at 0x219006897b8>,
 307612: <__main__.user_seq at 0x219006897f0>,
 1046782: <__main__.user_seq at 0x21900689828>,
 47841: <__main__.user_seq at 0x21900689860>,
 738018: <__main__.user_seq at 0x21900689898>,
 241058: <__main__.user_seq at 0x219006898d0>,
 1014282: <__main__.user_seq at 0x21900689908>,
 1293090: <__main__.user_seq at 0x21900689940>,
 1180298: <__main__.user_seq at 0x21900689978>,
 436733: <__main__.user_seq at 0x219006899b0>,
 547218: <__main__.user_seq at 0x219006899e8>,
 380844: <__main__.user_seq at 0x21900689a20>,
 1266749: <__main__.user_seq at 0x21900689a58>,
 130330: <__main__.user_seq at 0x21900689a90>,

#### 然后，就是从数据表中提出相应的信息，填入特征矩阵
这一块，我们基于之前的数据表提取特征了，也是分为这几块提取
* 用户的登录信息特征(launch表)
* 用户创作视频的信息特征(create表)
* 用户使用时的行为特征，例如点赞，转发等（activity表的act_type）
* 用户产生行为的界面信息特征(activity表的page字段)
* 用户观看其他用户的行为特征(activity表的author_id字段 != user_id)
* 观看自己作品的行为特征(activity表的author_id字段 == user_id)

##### 用户的登录信息特征 （是否在某天登录过）- launch表

In [11]:
# 看看launch表长啥样来
launch.head()

   user_id  launch_day
0   383135           1
1   330986           4
2   330986           9
3   330986          11
4   330986          12

In [23]:
launch['launch_freq'] = 1    # 每个用户每天登录次数
launch_table = launch.groupby(['user_id', 'launch_day'], as_index=False).agg({'launch_freq':'sum'})
launch_table.head()
# 如果这里的as_index为true， 那么这里的索引就自动变成第一列，也就是user_id，这五个会用共同的索引。  如果是False，那就是SQL风格的输出

   user_id  launch_day  launch_freq
0       16          13            1
1       16          14            1
2       16          15            1
3       16          18            1
4       16          19            1

In [24]:
# 然后得根据用户的id进行整合一下，把相同用户的结果放在一块
def record_to_sequence(table):    # 得到用户特征序列表
    table.columns = ['user_id', 'day', 'value']
    table.sort_values(by=['user_id', 'day'], inplace=True)
    table['string'] = table.day.map(str) + ":" + table.value.map(str)
    table = table.groupby(['user_id'], as_index=False).agg({'string':lambda x:','.join(x)})
    return table

In [25]:
launch_table = record_to_sequence(launch_table)
launch_table.head()

   user_id                                             string
0       16       13:1,14:1,15:1,18:1,19:1,20:1,21:1,22:1,23:1
1       30                                               24:1
2       98                                               16:1
3      105  12:1,14:1,15:1,16:1,17:1,18:1,19:1,20:1,21:1,2...
4      176                                27:1,28:1,29:1,30:1

In [26]:
"""然后我们把用户的登录信息填入到特征矩阵，是否登录的信息是第1列特征"""
# 例如ID=16的用户会在其特征表的指定位置的（13,14,15,18...行第1列进行填充）
for index, row in launch_table.iterrows():   # 根据登录信息对用户特征表进行填充
    data[row[0]].put_feature(0, row[1])      # row[0]就是用户ID， data[row[0]]就是用户对应的特征表，用put_feature函数将row[1],填入到第一列中

##### 创作视频的特征（是否在某天创建过视频） - create表

In [16]:
# 先看一下那个表的信息
create.head()

   user_id  create_day
0   720497           1
1   720497           1
2   720497           1
3  1075211           6
4  1075211          12

In [27]:
# 这个和上面的思路差不多，也是先进行统计，然后整合填充到第2列的特征
create['create_freq'] = 1
create_table = create.groupby(['user_id', 'create_day'], as_index=False).agg({'create_freq':'sum'})
create_table = record_to_sequence(create_table)
for index, row in create_table.iterrows():
    data[row[0]].put_feature(1, row[1])

##### 用户使用时的行为特征(activity表的act_type字段)
这一块根据是否有act_type字段的六种行为（播放，关注，点赞，转发，举报，减少此类作品）可以做出6个特征

In [28]:
# 看一下表中的信息
activity.head()
set(activity['page'])

{0, 1, 2, 3, 4}

In [29]:
"""这里使用的act_type字段，对于不同的行为，制作不同的特征，构建6个特征"""
for i in range(6):
    act_table = activity[activity.act_type==i].copy()    # 这个地方要深复制一下，不要动用原来的表
    act_table = act_table.groupby(['user_id', 'act_day'], as_index=False).agg({'video_id':'count'})
    act_table = record_to_sequence(act_table)
    for index, row in act_table.iterrows():
        data[row[0]].put_feature(i+2, row[1])

##### 用户产生行为的界面信息特征(activity表的page字段)

In [30]:
 for i in range(5):     
    act = activity[activity.page==i].copy()
    act = act.groupby(['user_id', 'act_day'], as_index=False).agg({'video_id':'count'})
    act = record_to_sequence(act)
    for index, row in act.iterrows():
        data[row[0]].put_feature(i+8, row[1])

##### 用户观看其他用户的行为特征(activity表的author_id字段 != user_id)

In [31]:
watched = register.loc[:, ['user_id']].copy()
watched.columns = ['author_id']
watched = pd.merge(watched, activity[activity.author_id != activity.user_id], how='inner')  # 只得到交集 相当于看别人视频的
watched = watched.groupby(['user_id', 'act_day'], as_index=False).agg({'video_id':'count'})
watched = record_to_sequence(watched)
for index, row in watched.iterrows():
    data[row[0]].put_feature(13, row[1])

##### 观看自己作品的行为特征(activity表的author_id字段 == user_id)

In [32]:
watched = activity[activity.author_id == activity.user_id].copy()
watched = watched.groupby(['user_id', 'act_day'], as_index=False).agg({'video_id':'count'})
watched = record_to_sequence(watched)
for index, row in watched.iterrows():
    data[row[0]].put_feature(14, row[1])

## 制作数据标签
通过上面的操作，我们就构建好了神经网络的输入，当然这里这样构建特征是为神经网络服务的，如果是想用机器学习的一些方式，就可以提取一些统计的特征，比如平均值，方差，中位数的这些东西用xgb什么的跑，但是这种时间之间的特征可能就捕捉不到了。<br><br>
下面，我们就是制作数据的标签了： 在未来七天内是否会使用APP， 这个的思路就是对用户从注册开始就进行统计，对于每1天的数据展开，如果其未来七天内这个用户活跃过，就标记为1

In [33]:
label = {user_id:user.get_label() for user_id, user in data.items()}
label

{744025: array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, None, None, None, None, None, None, None], dtype=object),
 1270299: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, None, None, None, None, None, None, None], dtype=object),
 571220: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, None, None, None, None, None, None, None], dtype=object),
 1308501: array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, None, None, None, None, None, None, None], dtype=object),
 745554: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, None, None, None, None, None, None, None], dtype=object),
 1031012: array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, None, None, None, None, None, None, None], dtype=object),
 913297: array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, None, None, None, None, None, None, None], dtype=object),
 266500: array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, None, None, None, None, None, None, None], dtype=object),
 475120: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, None, None, None, None, None, None, None], dtype=object),
 547944: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, None, None, None, None, None, None, None], dtype=object),
 916655: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 719262: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 1026175: array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        None, None, None, None, None, None, None], dtype=object),
 1140342: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 688100: array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 1342459: array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 926263: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 40710: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 246954: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 153579: array([0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 161418: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 649526: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 376694: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        None, None, None, None, None, None, None], dtype=object),
 1265894: array([1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 290029: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 926952: array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        None, None, None, None, None, None, None], dtype=object),
 70931: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 319938: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 711107: array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 872383: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 324085: array([1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 720967: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 895912: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 396421: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 605799: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 374225: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 188120: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 4416: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 245385: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 1244564: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None,
        None, None, None, None, None, None], dtype=object),
 321610: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None,
        None, None, None, None, None, None], dtype=object),
 998568: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, None, None,
        None, None, None, None, None], dtype=object),
 362447: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 508312: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 828824: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 604296: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 1040779: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 104515: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 909345: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 584573: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 809615: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 705594: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 544673: array([1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 1353252: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 1228936: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 130304: array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 636433: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 649913: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 300198: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 958588: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 365947: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 546663: array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 358836: array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None,
        None, None, None, None, None], dtype=object),
 572651: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None,
        None, None, None, None, None], dtype=object),
 200677: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 121072: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None,
        None, None, None, None], dtype=object),
 283372: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 1046808: array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None,
        None, None, None, None], dtype=object),
 286389: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 785752: array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 65439: array([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 1070734: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, None, None, None,
        None, None, None, None], dtype=object),
 409296: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None,
        None, None, None, None], dtype=object),
 507130: array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None,
        None, None, None, None], dtype=object),
 46089: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 363195: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None,
        None, None, None, None], dtype=object),
 826213: array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None,
        None, None, None], dtype=object),
 1095380: array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, None, None, None, None,
        None, None, None], dtype=object),
 742578: array([1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, None, None, None, None,
        None, None, None], dtype=object),
 278433: array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None,
        None, None, None], dtype=object),
 323276: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None,
        None, None, None], dtype=object),
 1080404: array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, None, None, None, None,
        None, None, None], dtype=object),
 371793: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None,
        None, None, None], dtype=object),
 581535: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None,
        None, None, None], dtype=object),
 623713: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None,
        None, None, None], dtype=object),
 613814: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None,
        None, None, None], dtype=object),
 1230657: array([1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, None, None, None, None,
        None, None, None], dtype=object),
 181217: array([0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 393403: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 647111: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 301007: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 1720: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 135240: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 1005097: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 1265157: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 422203: array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 491162: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 392276: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 1119103: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 493601: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 987199: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 428929: array([1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 764894: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 901027: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 716335: array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 1132054: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None,
        None, None], dtype=object),
 1201394: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 79180: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, None, None, None, None, None,
        None, None], dtype=object),
 363940: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 1171561: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, None, None, None, None, None,
        None, None], dtype=object),
 29588: array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, None, None, None, None, None,
        None, None], dtype=object),
 225105: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None,
        None], dtype=object),
 479488: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 1349377: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 755950: array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, None, None, None, None, None, None,
        None], dtype=object),
 867067: array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0, None, None, None, None, None, None,
        None], dtype=object),
 1208320: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 644685: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None,
        None], dtype=object),
 580269: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 1278006: array([1, 0, 0, 0, 0, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 900759: array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None,
        None], dtype=object),
 301088: array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 846124: array([1, 1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None,
        None], dtype=object),
 873341: array([1, 1, 1, 1, 1, 1, 1, 1, 0, None, None, None, None, None, None,
        None], dtype=object),
 373134: array([0, 0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None,
        None], dtype=object),
 547864: array([1, 1, 1, 1, 1, 1, 0, 1, None, None, None, None, None, None, None],
       dtype=object),
 1145926: array([1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 741300: array([0, 0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 685607: array([1, 1, 1, 1, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 1096768: array([1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 544078: array([1, 1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 500537: array([0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 1126528: array([1, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 470633: array([1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 1260044: array([1, 1, 1, 1, 1, 1, 0, None, None, None, None, None, None, None],
       dtype=object),
 1147129: array([1, 1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 708206: array([0, 0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 578505: array([1, 1, 1, 1, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 473398: array([1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 805787: array([0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 905493: array([1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 706631: array([1, 1, 1, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 875685: array([1, 1, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 969252: array([1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 24482: array([1, 1, 1, 1, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 935166: array([0, 0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 1316877: array([1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 1163109: array([1, 1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 657176: array([1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 1024790: array([0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 1216256: array([1, 1, 1, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 908794: array([1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 154609: array([0, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 1283254: array([1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 498488: array([1, 0, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 969395: array([1, 1, 1, 1, 1, None, None, None, None, None, None, None],
       dtype=object),
 64315: array([1, 1, 0, 0, 0, None, None, None, None, None, None, None],
       dtype=object),
 354563: array([0, 0, 0, 0, None, None, None, None, None, None, None], dtype=object),
 1356592: array([1, 1, 1, 1, None, None, None, None, None, None, None], dtype=object),
 706245: array([1, 1, 1, 1, None, None, None, None, None, None, None], dtype=object),
 173080: array([1, 1, 1, 1, None, None, None, None, None, None, None], dtype=object),
 315508: array([0, 0, 0, 0, None, None, None, None, None, None, None], dtype=object),

最后，把每一个用户对应的矩阵拿出来放入data， 特征制作完毕

In [34]:
data = {user_id: user.get_array() for user_id, user in data.items()}

In [37]:
data[744025].shape

(30, 15)

## 建立模型并且训练
通过上面的方式，我们已经把数据特征和标签都已经制作完毕，接下来就是建立RNN模型进行训练了，这里使用tensorflow来建立模型。

### 合并上述的提取方法，通过数据生成器进行获得

In [3]:
register=pd.read_csv('user_register_log.txt',sep='\t',names=['user_id','register_day','register_type','device_type'])
launch=pd.read_csv('app_launch_log.txt',sep='\t',names=['user_id','launch_day'])
create=pd.read_csv('video_create_log.txt',sep='\t',names=['user_id','create_day'])
activity=pd.read_csv('user_activity_log.txt',sep='\t',names=['user_id','act_day','page','video_id','author_id','act_type'])

data_generator=DataGenerator(register,launch,create,activity)

### 构建RNN网络模型并进行训练

In [4]:
n_features = 12
n_hu = 8
with tf.variable_scope('train'):     # tf.variable_scope用来指定变量的作用域
    
    # 变量与输入
    lr = tf.placeholder(tf.float32, [], name='learning_rate')    # 定义学习率
    
    # 隐藏层到输出层的参数w, b    w_shape(n_hu,1)   b_shape(1)  n_huWie隐藏单元的个数
    W_out = tf.get_variable('W_out', [n_hu, 1])   
    b_out = tf.get_variable('b_out', [1])
    
    # x和y  x_shape(batch_size, seq_length, n_features)
    x = tf.placeholder(tf.float32, [None, None, n_features])
    y = tf.placeholder(tf.float32, [None, None])
    
    # batch_size和seq_length的大小
    batch_size = tf.shape(x)[0]
    seq_length = tf.shape(x)[1]
    
    # RNN 层
    cell = tf.nn.rnn_cell.GRUCell(n_hu)     # n_hu表示每个GRUcell里面的单元个数
    initial_state = cell.zero_state(batch_size, dtype=tf.float32)   # 指定初识状态，因为之前没有训练过
    outputs, state = tf.nn.dynamic_rnn(cell, x, initial_state=initial_state)  # 使用的动态Rnn
    # outputs(batch_size, max_seq_length, n_hu)     这是所有时间步的输出
    # state (batch_size, n_hu)   这是最后一个时间步的输出
    # 具体：https://blog.csdn.net/u010960155/article/details/81707498
    
    # 输出层
    outputs = tf.reshape(outputs, [-1, n_hu])    # （batch_size*max_seq_length, n_hu）
    logits = tf.matmul(outputs, W_out) + b_out    # (batch_size*max_seq_length)
    logits = tf.reshape(logits, tf.stack([batch_size, seq_length]))

WARNING:tensorflow:From C:\Users\ZhongqiangWu\Anaconda3\envs\tfenv\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From <ipython-input-4-29e1f57edea9>:21: GRUCell.__init__ (from tensorflow.python.ops.rnn_cell_impl) is deprecated and will be removed in a future version.
Instructions for updating:
This class is equivalent as tf.keras.layers.GRUCell, and will be replaced by that in Tensorflow 2.0.
WARNING:tensorflow:From <ipython-input-4-29e1f57edea9>:23: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API

In [16]:
# 选择部分预测结果与标签当做训练损失计算
logits_local_train = logits[:, :-14] # 这里-14或者是更小，因为本地训练，我们用前16天训练，16-23天测试。
label_local_train = y[:, :-14]

In [17]:
# 设置损失函数

# 正则化项
regularizer = tf.contrib.layers.l2_regularizer(0.00001)
penalty = tf.contrib.layers.apply_regularization(regularizer, tf.trainable_variables())

obj_local = tf.losses.sigmoid_cross_entropy(label_local_train, logits_local_train) + penalty
optimizer = tf.train.AdamOptimizer(lr)
set_local = optimizer.minimize(obj_local)

# 选择部分预测结果与标签当做测试损失计算
logits_local_test = logits[:, -8]
label_local_test = y[:, -8]   #  这里也可以选择其他的天

In [18]:
def train(n_obs=1000, step=1000, lr_feed=0.01):
    #date_seq = [31] + list(range(2, 16)) + [16] * 15
    variables = [set_local, obj_local, label_local_train, logits_local_train]
    
    for i in range(step):
        length, id_list, data_x, data_y = data_generator.next_batch(n_obs)
        _, los, lab, log = sess.run(variables, 
                                   feed_dict={x:data_x, y:data_y, lr:lr_feed})

这里这个取数据的思路得说一下： 也就是next_batch操作
这里取数据的时候，这个序列长度并不是随机取的。 如果看next_batch函数的时候就会注意到， 首先是先有了local_random_list， 然后从这里面取序列的长度， 那么这个local_random_list做了个什么事情呢？  他不是1-30的序列长度随机选，因为不同序列长度的用户个数不一样，而大部分应该集中在15天及以后，1-14天的那种用户可能很少，这样就有可能不够一个batch_size。 所以尽量的选15天以后的，这个local_random_list里面的元素就是从15开始，然后越往后的元素个数越多，那么相应被选择的几率就越大。 这样无非就是选择序列的时候，对应的用户让他多一些，这样好取够batch_size。<br><br>
然后有了这个序列长度，我们就可以取相应的用户了，pointer指针就是为了从头开始选择用户数据，够一个batch_size为止，如果超了用户数目的长度，就回到头上，然后打乱用户数据，再取。 （这里建议看一下代码，只描述可能不知道咋回事， 在deep.tools.py）

In [19]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [20]:
train(n_obs=1000, step=2000, lr_feed=0.01)

### 模型测试并输出结果
f1值进行评估<br>
![](img/5.png)

In [21]:
def test():
    n_NA = 14     # 本地训练， 我们是1-16天训练，16-23天预测，所以这个地方最大是30-14
    # 优化目标和数据
    variables_1 = [obj_local, logits_local_train, label_local_train]
    variables_2 = [logits_local_test, label_local_test]
    
    obs_count, cum_loss, correct = 0, 0, 0
    user, prob, real = [], [], []
    
    # 训练损失
    for length, id_list, data_x, data_y in zip(*data_generator.get_set('train')):
        _obj, _logits_train, _label_train = sess.run(variables_1,
                                                    feed_dict={x:data_x, y:data_y, lr:0.001})
        obs_count += (length - n_NA) * len(id_list)
        cum_loss += _obj * (length - n_NA) * len(id_list)
        correct += np.sum((1 * (_logits_train>0) == _label_train))
    
    # 测试损失
    for length, id_list, data_x, data_y in zip(*data_generator.get_set('test')):
        _ = sess.run(variables_2, feed_dict={x:data_x, y:data_y, lr:0.001})
        _logits_test, _label_test = _
        real += list(_label_test)
        
        user += list(id_list)
        prob += list(1 / (1+np.exp(-_logits_test.reshape([-1]))))
    
    # 打印训练损失
    print('train_loss', cum_loss/obs_count)
    
    # 测试损失
    result = pd.DataFrame({'user_id':user, 'prob':prob, 'label':real})
    print('test_score:', f(result))
    
    return result

In [22]:
test()

train_loss 0.42956960269747707
test_score: [0.8053140974078207, 0.8054470655626724, 0.8050643507376791, 0.8053365676167374, 0.8047954268776796, 0.8040700300204564]

       user_id      prob  label
0      1274576  0.857779    1.0
1       109973  0.815846    1.0
2       134299  0.815846    0.0
3      1005835  0.595065    1.0
4       864582  0.820167    1.0
5      1293122  0.339015    1.0
6       896835  0.753712    1.0
7       630631  0.870561    1.0
8      1121791  0.753712    1.0
9      1038314  0.725725    1.0
10     1201628  0.339015    0.0
11     1323759  0.815846    1.0
12      281753  0.815846    1.0
13     1246728  0.780741    1.0
14     1280301  0.594126    0.0
15      403903  0.861102    1.0
16      456923  0.780741    1.0
17     1165819  0.594126    1.0
18      452121  0.339015    0.0
19      356773  0.815846    1.0
20     1362089  0.339015    1.0
21      767634  0.815846    1.0
22      254346  0.339015    0.0
23     1095295  0.861102    1.0
24     1171136  0.725725    1.0
25     1294875  0.476942    1.0
26      980295  0.339015    0.0
27      750139  0.870561    1.0
28       68475  0.815846    0.0
29      222996  0.720917    1.0
...        ...       ...    ...
37416   152532  0.052708    0.0
37417   756057  0.426611    1.0
37418  1346518  0.993903    1.0
37419    59116  0.883602    1.0
37420  1293977  0.650630    1.0
37421   530392  0.196013    0.0
37422  1005611  0.119434    0.0
37423   782747  0.048696    0.0
37424    13914  0.048696    0.0
37425   355141  0.369041    0.0
37426   255441  0.048696    0.0
37427    34878  0.052708    1.0
37428     2180  0.985193    0.0
37429   895107  0.991784    1.0
37430   220625  0.044650    0.0
37431  1156842  0.035504    0.0
37432   926700  0.035504    0.0
37433   183482  0.350676    0.0
37434   295353  0.147742    1.0
37435  1268644  0.988134    1.0
37436  1162278  0.537572    0.0
37437   385851  0.048316    0.0
37438   801029  0.048696    0.0
37439   173089  0.995543    1.0
37440    84785  0.044650    0.0
37441   801166  0.688787    1.0
37442  1079522  0.995127    1.0
37443   283730  0.324438    0.0
37444   632063  0.941044    1.0
37445   155347  0.048316    0.0

[37446 rows x 3 columns]

### 余弦退火 + 热重启训练思想
越来越接近loss值的全局最小值时，学习率应该变得越来越小来使得模型尽可能接近最小值。 然后突然提高学习率，来“跳出”局部最小值并找到通向全局最小值的路径。

In [26]:
def cos_annealing_local(epoch=5):
    all_result=None
    for i in range(epoch):
        train(step=2000,lr_feed=0.01)
        train(step=2000,lr_feed=0.001)
        result=test()
        print(sess.run(penalty))
        result.columns=['label','prob%s'%i,'user_id']
        if i==0:
            all_result=result
        else:
            all_result=pd.merge(all_result,result)
    return all_result

In [27]:
cos_annealing_local()

train_loss 0.4289520332444526
test_score: [0.8051643803524481, 0.8053407190635452, 0.8052916163578141, 0.8053609664543075, 0.8051175877262833, 0.8046993632948825]
0.0006277356
train_loss 0.4288679725521854
test_score: [0.8057853389521876, 0.8057455898927944, 0.8056542683408355, 0.8056776117813108, 0.8056491734874018, 0.8052826542116283]
0.00073696766
train_loss 0.42884548220977986
test_score: [0.8056395288231003, 0.805784473255997, 0.8058009228740936, 0.8053310723086299, 0.8054410110855245, 0.8056010965678502]
0.0008184217
train_loss 0.4286306096566724
test_score: [0.8057680836164639, 0.8055208333333332, 0.8058191349934469, 0.806068427845234, 0.8057995555085194, 0.8058112157534247]
0.000890288
train_loss 0.42857027057252495
test_score: [0.8060728326091454, 0.8059306190278355, 0.8060544271037566, 0.8058558085843216, 0.8056954515491102, 0.8058762364358654]
0.00093093584

         label     prob0  user_id     prob1     prob2     prob3     prob4
0      1274576  0.856154      1.0  0.840750  0.849629  0.849199  0.851723
1       109973  0.815051      1.0  0.805713  0.812808  0.815035  0.813512
2       134299  0.815051      0.0  0.805713  0.812808  0.815035  0.813512
3      1005835  0.586597      1.0  0.560536  0.565540  0.566560  0.570088
4       864582  0.828008      1.0  0.821973  0.824899  0.831624  0.826582
5      1293122  0.334039      1.0  0.323247  0.324855  0.324347  0.333743
6       896835  0.759586      1.0  0.746464  0.755796  0.762776  0.764424
7       630631  0.875573      1.0  0.872625  0.876371  0.883951  0.881113
8      1121791  0.759586      1.0  0.746464  0.755796  0.762776  0.764424
9      1038314  0.719833      1.0  0.701582  0.709675  0.716737  0.718184
10     1201628  0.334039      0.0  0.323247  0.324855  0.324347  0.333743
11     1323759  0.815051      1.0  0.805713  0.812808  0.815035  0.813512
12      281753  0.815051      1.0  0.805713  0.812808  0.815035  0.813512
13     1246728  0.779653      1.0  0.766802  0.772253  0.769421  0.771130
14     1280301  0.608566      0.0  0.597316  0.604974  0.615414  0.619901
15      403903  0.879230      1.0  0.867464  0.863347  0.866864  0.865512
16      456923  0.779653      1.0  0.766802  0.772253  0.769421  0.771130
17     1165819  0.608566      1.0  0.597316  0.604974  0.615414  0.619901
18      452121  0.334039      0.0  0.323247  0.324855  0.324347  0.333743
19      356773  0.815051      1.0  0.805713  0.812808  0.815035  0.813512
20     1362089  0.334039      1.0  0.323247  0.324855  0.324347  0.333743
21      767634  0.815051      1.0  0.805713  0.812808  0.815035  0.813512
22      254346  0.334039      0.0  0.323247  0.324855  0.324347  0.333743
23     1095295  0.879230      1.0  0.867464  0.863347  0.866864  0.865512
24     1171136  0.719833      1.0  0.701582  0.709675  0.716737  0.718184
25     1294875  0.509776      1.0  0.538221  0.548335  0.540575  0.551494
26      980295  0.334039      0.0  0.323247  0.324855  0.324347  0.333743
27      750139  0.875573      1.0  0.872625  0.876371  0.883951  0.881113
28       68475  0.815051      0.0  0.805713  0.812808  0.815035  0.813512
29      222996  0.721405      1.0  0.709471  0.716991  0.725464  0.733337
...        ...       ...      ...       ...       ...       ...       ...
37416  1365882  0.074349      0.0  0.081333  0.076139  0.079878  0.078736
37417   153929  0.384163      0.0  0.404933  0.406546  0.429834  0.434140
37418  1289965  0.085469      0.0  0.091056  0.084964  0.088504  0.089599
37419   257018  0.806826      1.0  0.794847  0.793067  0.797988  0.806273
37420   682300  0.251423      0.0  0.271812  0.267450  0.285337  0.285994
37421  1352716  0.532982      0.0  0.517310  0.495953  0.501366  0.495675
37422   312710  0.059826      0.0  0.062380  0.059203  0.062002  0.060839
37423   242322  0.112528      0.0  0.126716  0.122175  0.130670  0.129997
37424   238643  0.056587      0.0  0.059545  0.057826  0.061902  0.062206
37425  1126836  0.057074      0.0  0.060631  0.059829  0.062802  0.062319
37426  1017078  0.202663      0.0  0.223152  0.200971  0.180756  0.186007
37427   644615  0.190682      0.0  0.200602  0.187534  0.186185  0.186193
37428   710448  0.828474      0.0  0.828285  0.831334  0.841070  0.849227
37429    83372  0.099061      0.0  0.113464  0.109031  0.108026  0.112161
37430   532344  0.986800      1.0  0.985036  0.985481  0.984544  0.985095
37431   895107  0.992130      1.0  0.992813  0.993311  0.994419  0.995025
37432    80153  0.056587      0.0  0.059545  0.057826  0.061902  0.062206
37433  1234134  0.038840      0.0  0.038450  0.038596  0.040934  0.040738
37434  1033197  0.603401      1.0  0.596606  0.580291  0.590333  0.602344
37435  1349160  0.987025      1.0  0.986273  0.987573  0.988176  0.988502
37436   802750  0.114420      0.0  0.123679  0.122185  0.121040  0.128050
37437  1323915  0.063303      1.0  0.066976  0.065082  0.068803  0.069432
37438   913442  0.038840      0.0  0.038450  0.038596  0.040934  0.040738
37439  1087584  0.160184      1.0  0.175749  0.155595  0.165223  0.154660
37440   163202  0.055554      0.0  0.061184  0.059346  0.064086  0.064089
37441    75693  0.435010      0.0  0.462595  0.458981  0.480595  0.499257
37442  1076639  0.060848      0.0  0.064616  0.062157  0.064492  0.064106
37443   233831  0.876775      1.0  0.861200  0.856344  0.862963  0.861721
37444   919931  0.593517      0.0  0.626643  0.635944  0.656462  0.657430
37445  1184768  0.870457      1.0  0.852415  0.855199  0.867142  0.861434

[37446 rows x 7 columns]

## 知识点和思路的总结
1. pd.iterrows()函数
2. pd.groupby()函数

### pd.iterrows()函数
iterrows() 是在DataFrame中的行进行迭代的一个生成器，它返回每行的索引及一个包含行本身的对象。<br><br>
所以，当我们在需要遍历行数据的时候，就可以使用 iterrows()方法实现了。

In [31]:
df = pd.DataFrame(np.random.randn(3, 4), columns=list('ABCD'))
df

          A         B         C         D
0 -1.083707  0.856265 -0.254691  0.238692
1 -0.930010  0.969821 -0.912533  1.141066
2  0.132397  0.958107  0.004362 -1.627512

In [37]:
# 遍历行
for index, row in df.iterrows():    # index表示索引， row是一个Series结构，可以通过列名或者列索引来获取每一个元素
    print(index)
    print(row['A'])           # 这样是第一列的数据
    print(row[-1])   # 最后一列的数据
    print(row[1])    # 第二列的数据

0
-1.083706901708258
0.23869180151476993
0.8562654567977414
1
-0.930009726608264
1.1410662746749882
0.9698209735433845
2
0.1323970363518363
-1.6275121717858587
0.9581073260783397

### pd.groupby函数
这个函数的功能非常强大，类似于sql的groupby函数，对数据按照某一标准进行分组，然后进行一些统计。任何groupby操作都会涉及到下面的三个操作之一：
* Splitting：分割数据
* Applying：应用一个函数
* Combining:合并结果

在许多情况下，我们将数据分成几组，并在每个子集上应用一些功能。在应用中，我们可以执行以下操作：
* Aggregation ：计算一些摘要统计
* Transformation ：执行一些特定组的操作
* Filtration：根据某些条件下丢弃数据

参考博客：
* [Pandas之groupby( )用法笔记](https://www.cnblogs.com/bjwu/p/8970818.html)
* [Pandas分组运算（groupby）修炼](https://www.cnblogs.com/lemonbit/p/6810972.html)

In [40]:
ipl_data = {'Team': ['Riders', 'Riders', 'Devils', 'Devils', 'Kings',
         'kings', 'Kings', 'Kings', 'Riders', 'Royals', 'Royals', 'Riders'],
         'Rank': [1, 2, 2, 3, 3,4 ,1 ,1,2 , 4,1,2],
         'Year': [2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
         'Points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

#### Pandas对象可以拆分为任何对象。分割对象的方法有多种：
* obj.groupby('key')
* obj.groupby(['key1','key2'])
* obj.groupby(key,axis=1)

现在让我们看看如何将分组对象应用于DataFrame对象

In [41]:
df.groupby('Team')

In [76]:
# 查看分组
df.groupby('Team').groups   # 第几个是

{'Devils': Int64Index([2, 3], dtype='int64'),
 'Kings': Int64Index([4, 6, 7], dtype='int64'),
 'Riders': Int64Index([0, 1, 8, 11], dtype='int64'),
 'Royals': Int64Index([9, 10], dtype='int64'),
 'kings': Int64Index([5], dtype='int64')}

In [43]:
# 根据多列进行分组
df.groupby(['Team', 'Year']).groups

{('Devils', 2014): Int64Index([2], dtype='int64'),
 ('Devils', 2015): Int64Index([3], dtype='int64'),
 ('Kings', 2014): Int64Index([4], dtype='int64'),
 ('Kings', 2016): Int64Index([6], dtype='int64'),
 ('Kings', 2017): Int64Index([7], dtype='int64'),
 ('Riders', 2014): Int64Index([0], dtype='int64'),
 ('Riders', 2015): Int64Index([1], dtype='int64'),
 ('Riders', 2016): Int64Index([8], dtype='int64'),
 ('Riders', 2017): Int64Index([11], dtype='int64'),
 ('Royals', 2014): Int64Index([9], dtype='int64'),
 ('Royals', 2015): Int64Index([10], dtype='int64'),
 ('kings', 2015): Int64Index([5], dtype='int64')}

In [86]:
# 遍历分组
grouped = df.groupby('Rank', as_index=False)
for name in grouped:
    print(name)

(1,       Team  Rank  Year  Points
0   Riders     1  2014     876
6    Kings     1  2016     756
7    Kings     1  2017     788
10  Royals     1  2015     804)
(2,       Team  Rank  Year  Points
1   Riders     2  2015     789
2   Devils     2  2014     863
8   Riders     2  2016     694
11  Riders     2  2017     690)
(3,      Team  Rank  Year  Points
3  Devils     3  2015     673
4   Kings     3  2014     741)
(4,      Team  Rank  Year  Points
5   kings     4  2015     812
9  Royals     4  2014     701)

#### 获取某一分组  get_group方法

In [45]:
# 获取某一分组
grouped = df.groupby('Year')
print(grouped.get_group(2014))

     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701

#### Aggregations（聚合）
聚合函数返回每个组的单个聚合值。一旦创建了group by对象，就可以对分组数据执行多个聚合操作。

In [87]:
"""agg方法实现聚合, 相比于apply，可以同时传入多个统计函数"""

# 针对同一列使用不同的统计方法 
grouped = df.groupby('Year', as_index=False)    # 这个as_index属性，如果是False，就是SQL风格的统计输出，如果是True，默认第一列变成了索引
print(grouped['Points'].agg({'mean':np.mean, 'std':np.std, 'max':np.max}))

# 针对不同的列使用不同的统计方法
print(grouped.agg({'Points':[np.mean, 'sum'], 'Rank':[np.max]}))

# 使用apply的话
print(grouped['Points'].apply(np.mean))
grouped.apply(lambda x: print(x))

   Year    mean        std  max
0  2014  795.25  87.439026  876
1  2015  769.50  65.035888  812
2  2016  725.00  43.840620  756
3  2017  739.00  69.296465  788
   Year  Points       Rank
           mean   sum amax
0  2014  795.25  3181    4
1  2015  769.50  3078    4
2  2016  725.00  1450    2
3  2017  739.00  1478    2
0    795.25
1    769.50
2    725.00
3    739.00
dtype: float64
     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
     Team  Rank  Year  Points
0  Riders     1  2014     876
2  Devils     2  2014     863
4   Kings     3  2014     741
9  Royals     4  2014     701
      Team  Rank  Year  Points
1   Riders     2  2015     789
3   Devils     3  2015     673
5    kings     4  2015     812
10  Royals     1  2015     804
     Team  Rank  Year  Points
6   Kings     1  2016     756
8  Riders     2  2016     694
      Team  Rank  Year  Points
7    Kings     1  2017     788
11  Riders     2  2017     690

Empty DataFrame
Columns: []
Index: []

In [61]:
"""查看每个组大小的另一种方法是应用size()函数"""

grouped = df.groupby('Team')
print(grouped.size())
print(grouped.count())
print(grouped.agg(np.size))

Team
Devils    2
Kings     3
Riders    4
Royals    2
kings     1
dtype: int64
        Rank  Year  Points
Team
Devils     2     2       2
Kings      3     3       3
Riders     4     4       4
Royals     2     2       2
kings      1     1       1
        Rank  Year  Points
Team
Devils     2     2       2
Kings      3     3       3
Riders     4     4       4
Royals     2     2       2
kings      1     1       1

#### Transformations
前面进行聚合运算的时候，得到的结果是一个以分组名为 index 的结果对象。如果我们想使用原数组的 index 的话，就需要进行 merge 转换。transform(func, args, *kwargs) 方法简化了这个过程，它会把 func 参数应用到所有分组，然后把结果放置到原数组的 index 上（如果结果是一个标量，就进行广播）：

In [63]:
grouped = df.groupby('Team')
score = lambda x: (x - x.mean()) / x.std()*10
print(grouped.transform(score))   # 应用于原数组的index上

         Rank       Year     Points
0  -15.000000 -11.618950  12.843272
1    5.000000  -3.872983   3.020286
2   -7.071068  -7.071068   7.071068
3    7.071068   7.071068  -7.071068
4   11.547005 -10.910895  -8.608621
5         NaN        NaN        NaN
6   -5.773503   2.182179  -2.360428
7   -5.773503   8.728716  10.969049
8    5.000000   3.872983  -7.705963
9    7.071068  -7.071068  -7.071068
10  -7.071068   7.071068   7.071068
11   5.000000  11.618950  -8.157595

In [65]:
print(grouped.transform(lambda x: print(x)))

2    2
3    3
Name: Rank, dtype: int64
2    2014
3    2015
Name: Year, dtype: int64
2    863
3    673
Name: Points, dtype: int64
   Rank  Year  Points
2     2  2014     863
3     3  2015     673
4    3
6    1
7    1
Name: Rank, dtype: int64
4    2014
6    2016
7    2017
Name: Year, dtype: int64
4    741
6    756
7    788
Name: Points, dtype: int64
0     1
1     2
8     2
11    2
Name: Rank, dtype: int64
0     2014
1     2015
8     2016
11    2017
Name: Year, dtype: int64
0     876
1     789
8     694
11    690
Name: Points, dtype: int64
9     4
10    1
Name: Rank, dtype: int64
9     2014
10    2015
Name: Year, dtype: int64
9     701
10    804
Name: Points, dtype: int64
5    4
Name: Rank, dtype: int64
5    2015
Name: Year, dtype: int64
5    812
Name: Points, dtype: int64
    Rank  Year Points
0   None  None   None
1   None  None   None
2   None  None   None
3   None  None   None
4   None  None   None
5   None  None   None
6   None  None   None
7   None  None   None
8   None  None   None
9   None  None   None
10  None  None   None
11  None  None   None

In [64]:
print(grouped.agg(lambda x: print(x)))

2    2
3    3
Name: Rank, dtype: int64
4    3
6    1
7    1
Name: Rank, dtype: int64
0     1
1     2
8     2
11    2
Name: Rank, dtype: int64
9     4
10    1
Name: Rank, dtype: int64
5    4
Name: Rank, dtype: int64
2    2014
3    2015
Name: Year, dtype: int64
4    2014
6    2016
7    2017
Name: Year, dtype: int64
0     2014
1     2015
8     2016
11    2017
Name: Year, dtype: int64
9     2014
10    2015
Name: Year, dtype: int64
5    2015
Name: Year, dtype: int64
2    863
3    673
Name: Points, dtype: int64
4    741
6    756
7    788
Name: Points, dtype: int64
0     876
1     789
8     694
11    690
Name: Points, dtype: int64
9     701
10    804
Name: Points, dtype: int64
5    812
Name: Points, dtype: int64
        Rank  Year Points
Team
Devils  None  None   None
Kings   None  None   None
Riders  None  None   None
Royals  None  None   None
kings   None  None   None

In [68]:
print(grouped.apply(lambda x: print(x)))

     Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673
     Team  Rank  Year  Points
2  Devils     2  2014     863
3  Devils     3  2015     673
    Team  Rank  Year  Points
4  Kings     3  2014     741
6  Kings     1  2016     756
7  Kings     1  2017     788
      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
8   Riders     2  2016     694
11  Riders     2  2017     690
      Team  Rank  Year  Points
9   Royals     4  2014     701
10  Royals     1  2015     804
    Team  Rank  Year  Points
5  kings     4  2015     812
Empty DataFrame
Columns: []
Index: []

使用apply()处理的对象是一个个的类如DataFrame的数据表，然而agg()则每次只传入一列,从列的角度进行输出。

#### Filtration
过滤数据

In [70]:
grouped.size()

Team
Devils    2
Kings     3
Riders    4
Royals    2
kings     1
dtype: int64

In [69]:
print(df.groupby('Team').filter(lambda x: len(x) >= 3))

      Team  Rank  Year  Points
0   Riders     1  2014     876
1   Riders     2  2015     789
4    Kings     3  2014     741
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
11  Riders     2  2017     690